# Generated by Django 4.1.7 on 2023-03-13 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schoolapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="adminhod",
            name="email",
        ),
        migrations.RemoveField(
            model_name="adminhod",
            name="name",
        ),
        migrations.RemoveField(
            model_name="adminhod",
            name="passwrd",
        ),
        migrations.RemoveField(
            model_name="staffs",
            name="email",
        ),
        migrations.RemoveField(
            model_name="staffs",
            name="name",
        ),
        migrations.RemoveField(
            model_name="staffs",
            name="passwrd",
        ),
        migrations.RemoveField(
            model_name="students",
            name="email",
        ),
        migrations.RemoveField(
            model_name="students",
            name="name",
        ),
        migrations.RemoveField(
            model_name="students",
            name="passwrd",
        ),
    ]
